### ISSUE TITLE
miceMNAR imputation for data with multiple features having missingness

### ISSUE THREAD

**Issue by akhsassoualid** [cran/miceMNAR#1]
Hello, thanks a lot for your work on the miceMNAR package.
I have a dataset with around 90 features, most of them have missing values, my analysis shows an MNAR missingness mechanism, so I want to use your package to impute them. The problem is that the example shown in miceMNAR CRAN, implement an example with only a one feature having missed values, I'm wondering how to use miceMNAR for multiple features having missingness.
Thanks

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Thanks!
